### ISSUE TITLE
VCKICK COMMAND

### ISSUE THREAD

**Issue by hithereimxplicit** [oadpoaw/amongusbot#13]
Seems to not be allowing me to votekick. 
![image](https://user-images.githubusercontent.com/73083704/98469632-c51d7400-21ae-11eb-9ad1-3636871668c2.png)

**Comment by ehcac1024** [comment]
Its because you dont have the permission to do it so. You should be the "Lobby Owner" so you can run the command OR you have the moderator role as set in the config.json

edit: Lobby Owner by i mean HOST
