### ISSUE TITLE
Emergency

### ISSUE THREAD

**Issue by ZeroDiscord** [oadpoaw/amongusbot#5]
## Random Bug 
**bro this ain't good**
When I try to deploy the bot it says 
```sh
.      　。　　　　•　    　ﾟ　　。
　　.　　　.　　　  　　.　　　　　。　　   。　.
  　.　　      。　        ඞ   。　    .    •
    •        Zero was the imposter　 。　.
　 　　。　　 　　　　ﾟ　　　.
```
**This is cursed help me**

**Comment by ehcac1024** [comment]
im marking this as a duplicate, enhancement and good first issue, well done! LMAO xd

**Comment by ZeroDiscord** [comment]
I wouldn't close this until you remove the duplicate cuz y e s

**Comment by ehcac1024** [comment]
ok so, im marking this as invalid
